### ISSUE TITLE
How to use Dataset API

### ISSUE THREAD

**Issue by lukebuehler** [Microsoft/Mobius#595] opened 2016-10-28 20:53 UTC
According to the issues here it seems that the Dataset API has been implemented but I cannot figure out how to use it. Are there any examples, samples?

**Comment by skaarthik** [comment] 2016-11-02 05:58
@lukebuehler Dataset API in Mobius is limited and that is by design. See the comments in https://github.com/Microsoft/Mobius/blob/master/csharp/Adapter/Microsoft.Spark.CSharp/Sql/Dataset.cs#L118. It is recommended to use DataFrame API in Mobius.

**Comment by lukebuehler** [comment] 2016-11-02 13:42
@skaarthik , I see. But then my concern is how to make the best use Mobius, the comment states:
> It would offer static type checking at the cost of runtime optimizations because C# functionality need to execute in CLR

So, how would I go about using static typing, i.e. my own classes, and complex C# logic (thousands of lines of code) in Mobius, without having to push everything down into the DataFrame API (which in my case seems no possible)?

**Comment by skaarthik** [comment] 2016-11-02 19:49
@lukebuehler if you have complex C# logic and want to reuse existing classes, I think the best bet is to use RDD API even though it cannot leverage optimizations in DataFrame & Dataset API. Note that using lot of C# UDFs with DataFrame API (without static type checking) is not a good option either considering the performance overhead.

**Comment by lukebuehler** [comment] 2016-11-02 22:15
@skaarthik Thank you this is what I was wondering!

Do you have, by any chance, an example how to use SQL to get a DataFrame and then to convert it to a C# class?

**Comment by skaarthik** [comment] 2017-01-28 09:56
@lukebuehler - I do not have an example for the scenario you described. 

Closing this issue. Feel free to reopen if needed.

**Closed by skaarthik** 2017-01-28 09:56 UTC
