### ISSUE TITLE
NET Core

### ISSUE THREAD

**Issue by EdStone** [Microsoft/Mobius#647] opened 2017-03-28 07:53 UTC
Hi All:

Was Mobius tested on Ubuntu under NET Core?
Do you expect any issues / problems?

Thank you,
E

**Comment by cricket007** [comment] 2017-03-29 02:49
Duplicate #601

**Comment by skaarthik** [comment] 2017-03-29 04:49
@cricket007 thanks for marking this a duplicate of #601 
@EdStone  last year someone ran static check on Mobius code for .NET Core compliance and there were several red flags. I do not have that list handy now but the work involved to support in .NET Core did not seem trivial.

**Comment by skaarthik** [comment] 2017-04-09 03:37
Closing the issue due to inactivity. Feel free to reopen if there are additional questions on this topic.

**Closed by skaarthik** 2017-04-09 03:37 UTC
