### ISSUE TITLE
Implement a Daemon process to take charge of launching Worker processes

### ISSUE THREAD

**Issue by kai-zeng** [Microsoft/Mobius#155] opened 2015-12-10 23:48 UTC
On linux, [PythongWorkerFactory] (https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/api/python/PythonWorkerFactory.scala) launches worker processes through a daemon process. To be linux compatible, we need to implement a daemon process similar to [daemon.py] (https://github.com/apache/spark/blob/master/python/pyspark/daemon.py) in pyspark.

**Comment by ms-guizha** [comment] 2016-01-15 02:39
any one who has access to assign this bug to me

**Comment by kai-zeng** [comment] 2016-01-15 02:40
@ms-guizha Assigned to you. Thank you, Joe!

**Comment by danielli90** [comment] 2016-01-15 02:59
Thanks Joe. As you work on this issue/prototype, can you create a brief design along the way, so we can have design discussions as well?

**Comment by ms-guizha** [comment] 2016-01-15 04:39
I just got this issue and has not begun on. I will create a brief deign and discuss first

**Comment by ohwang** [comment] 2016-01-19 00:43
It looks like the reason that ``pyspark`` and ``sparkR`` prefer to launch workers from daemon is because it is cheaper compared with forking directly from JVM (which is expensive because JVM process itself is usually expensive). In other words, this can be considered as some *optimization* that is only available for Linux now.

If the purpose is mainly to be Linux compatible then it is possible to fall back to daemon-less style in Linux in one way or another, e.g. 

1. by override ``useDaemon`` in ``PythonWorkerFactory`` to let it always be ``false`` for SparkCLR
```.scala
  val useDaemon = !System.getProperty("os.name").startsWith("Windows")
```

2. Add a setting similar to ``spark.sparkr.use.daemon`` so that the value can be set to ``false`` for SparkCLR.


However, if the purpose is the gain from the optimization then there are a few considerations here

1. Will the daemon also work for Windows? How much performance gain will we get from it?

2. Should we investigate how to let the python/R's daemons work on Windows? (Closely related to how the C# daemon can be made to work for Windows)

3. Will there be positive impact for people using SparkCLR in Linux in the short term?

What do you guys think?

**Comment by kai-zeng** [comment] 2016-01-19 18:24
The main purpose is to be Linux compatible. However, we prefer not to override useDaemon or add a config parameter because it's better to keep the Spark core unchanged.
And of course, using Daemon on Linux can also bring performance advantages.

In short, implementing such a Daemon process is to make SparkCLR work in the same way as pyspark or sparkR, i.e.,
(1) use Daemon to launch worker on Linux,
(2) fall back to launching wokers directly on Windows

Investigating whether we can or should support daemon on Windows is interesting and important. But I would say it's out of the scope of this issue. Actually, if daemon does work for Windows, we should push a PR to Spark core instead of SparkCLR only, so that pyspark and sparkR can benefit from this too.

**Comment by guiling** [comment] 2016-03-11 03:23
Kai has confirmed with  our multi-threading approach is viable.The reason they used a multi-processing approach because python does not have a good threading support. 

so maybe we need merge this work item with Tao Qin's performance improvement item

**Closed** 2016-04-19 04:57 UTC
Labels: bug, Deployment, up for grabs
