### ISSUE TITLE
examples folder in release zip does not have binaries

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/Mobius#289] opened 2016-02-01 05:50 UTC
The release zip file includes source files under "examples" folder. Source files need to be replaced with binaries that can be run directly without the need to build.

https://github.com/Microsoft/SparkCLR/releases/download/v1.5.200/spark-clr_2.10-1.5.200.zip

**Comment by skaarthik** [comment] 2016-02-05 01:32
With https://github.com/Microsoft/SparkCLR/pull/294 example projects are built. Need to include them in "runtime" folder that will be used for release.

**Comment by hebinhuang** [comment] 2016-04-21 04:57
Checked in #400

**Comment by skaarthik** [comment] 2016-04-21 06:29
@hebinhuang - the latest release https://github.com/Microsoft/Mobius/releases/tag/v1.6.100-PREVIEW-1 does not seem to have example binaries. Can you take a look? You can refer to the logs of build 1.6.1-SNAPSHOT.685 in AppVeyor to troubleshoot.

**Comment by hebinhuang** [comment] 2016-04-21 11:43
It caused by the failure of compiling Examples.

HdfsWordCount -> C:\projects\sparkclr\examples\Streaming\HdfsWordCount\bin\Debug\SparkClrHdfsWordCount.exe
 1204C:\windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "CSharpWorker". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\projects\sparkclr\examples\Sql\JdbcDataFrame\JdbcDataFrame.csproj]
 1205C:\windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Spark.CSharp.Adapter". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\projects\sparkclr\examples\Sql\JdbcDataFrame\JdbcDataFrame.csproj]
 1206Program.cs(6,30): error CS0234: The type or namespace name 'Core' does not exist in the namespace 'Microsoft.Spark.CSharp' (are you missing an assembly reference?) [C:\projects\sparkclr\examples\Sql\JdbcDataFrame\JdbcDataFrame.csproj]
 1207Program.cs(7,30): error CS0234: The type or namespace name 'Services' does not exist in the namespace 'Microsoft.Spark.CSharp' (are you missing an assembly reference?) [C:\projects\sparkclr\examples\Sql\JdbcDataFrame\JdbcDataFrame.csproj]
 1208Program.cs(8,30): error CS0234: The type or namespace name 'Sql' does not exist in the namespace 'Microsoft.Spark.CSharp' (are you missing an assembly reference?) [C:\projects\sparkclr\examples\Sql\JdbcDataFrame\JdbcDataFrame.csproj]
 1209C:\projects\sparkclr\examples\Sql\SparkXml\SparkXml.csproj(43,5): error MSB4067: The element <#text> beneath element <Reference> is unrecognized.
 1210C:\windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "CSharpWorker". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\projects\sparkclr\examples\Streaming\EventHub\EventHub.csproj]
 1211  EventHub -> C:\projects\sparkclr\examples\Streaming\EventHub\bin\Debug\SparkClrEventHub.exe
 1212  Pi -> C:\projects\sparkclr\examples\Batch\Pi\bin\Debug\SparkClrPi.exe
 1213  WordCount -> C:\projects\sparkclr\examples\Batch\WordCount\bin\Debug\SparkClrWordCount.exe
 1214MessagePublisher.cs(40,17): warning CS0219: The variable 'topicName' is assigned but its value is never used [C:\projects\sparkclr\examples\Streaming\Kafka\Kafka.csproj]
 1215  Kafka -> C:\projects\sparkclr\examples\Streaming\Kafka\bin\Debug\SparkClrKafka.exe
 1216===== Build FAILED for C:\projects\sparkclr\examples\Examples.sln -- Debug with error 1 - CANNOT CONTINUE =====

**Closed** 2016-04-21 12:14 UTC
