### ISSUE TITLE
Issue with HiveDataFrame example execution

### ISSUE THREAD

**Issue by ramkumarravy** [Microsoft/Mobius#575] opened 2016-10-05 07:17 UTC
While running HiveDataFrame example, following exception gets thrown in the HiveContext creation line.

> {"JVM method execution failed: Static method createHiveContext failed for class org.apache.spark.sql.api.csharp.SQLUtils when called with 1 parameters ([Index=1, Type=JvmObjectReference, Value=4], )"}

Also this error:

> [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - java.lang.IllegalArgumentException: System memory 259522560 must be at least 471859200. Please increase heap size using the --driver-memory option or spark.driver.memory in Spark configuration.

For your information, I am running the sample in "Debug" mode and I've also referred the external JARS (hope, not required for this) as suggested here: https://github.com/Microsoft/Mobius/issues/450 

Please refer to the logs from the screenshot below.

![mobius](https://cloud.githubusercontent.com/assets/22632483/19104388/d7c5118a-8af9-11e6-8c2a-13c4a608dc6d.png)

Please help me resolving this... Thanks!

**Comment by skaarthik** [comment] 2016-10-05 17:59
The second error message is the root cause. You can either set `spark.driver.memory` in Spark configuration file or set it in your code like `sparkConf.Set("spark.driver.memory", "512m")`. If you are running your Mobius app in normal mode (i.e. not in  debug mode) you could also use `--driver-memory` option in the command line. HTH.

**Comment by ramkumarravy** [comment] 2016-10-05 18:14
I've tried setting the memory option in the sample (refer to the screenshot below), but still facing the same memory exception.

![sshot-2](https://cloud.githubusercontent.com/assets/22632483/19125689/ab238f1a-8b55-11e6-9ead-aa25f6558726.png)

**Comment by ramkumarravy** [comment] 2016-10-05 18:17
As per steps listed for "debug" mode, I've started service for the CSharpBackend and have modified the port number/worker path in my C# application. Doesn't this mean running the sample in debug mode or is this normal mode ?

**Comment by skaarthik** [comment] 2016-10-05 18:45
Yes - the steps you have followed is for debug mode.

It looks like setting the config in code like `sparkConf.Set("spark.driver.memory", "512m")` does not help. See https://stackoverflow.com/questions/39023022/how-to-set-heap-size-in-spark-within-the-eclispe-environment for details. Try following the other option I suggested - to update the Spark config file.

Another option is to set the `-Xmx512m` setting instead of updating the Spark config file. Replace [Line 81](https://github.com/Microsoft/Mobius/blob/master/scripts/sparkclr-submit.cmd#L81) in sparkclr-submit.cmd under `runtime\scripts` folder in your Mobius build (or downloaded release) with the following and try launching it in debug mode.

`"%JAVA_HOME%\bin\java" -Xmx512m -cp "%LAUNCH_CLASSPATH%" org.apache.spark.deploy.csharp.CSharpRunner debug`

Note that I am using `512m` as an example. If you can, try allocating more memory.

**Comment by ramkumarravy** [comment] 2016-10-05 18:52
Thanks Kaarthik!! Now the memory exception issue has been resolved. But, still I could face the hive context creation error (please refer below)

{"JVM method execution failed: Static method createHiveContext failed for class org.apache.spark.sql.api.csharp.SQLUtils when called with 1 parameters ([Index=1, Type=JvmObjectReference, Value=4], )"}

**Comment by skaarthik** [comment] 2016-10-05 21:29
Can you share the log messages from the output of sparkclr-submit.cmd? 
BTW, what Metastore are you using for Hive that you are trying to connect to? I am wondering if you need to include the jar for connecting to it.

**Comment by ramkumarravy** [comment] 2016-10-06 09:29
I'd to know whether Mobius supports Spark ML/MLlib APIs ? here's the logs for your reference.

[sparkclr-submit.cmd] SPARKCLR_JAR=spark-clr_2.11-2.0.000-SNAPSHOT.jar
[sparkclr-submit.cmd] LAUNCH_CLASSPATH="D:\VisualAnalytics\Mobius-master\build\runtime\lib\spark-clr_2.11-2.0.000-SNAPSHOT.jar;D:\VisualAnalytics\Mobius-master\build\tools\spark-2.0.0-bin-hadoop2.7\jars\*"
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/10/06 14:56:42 INFO CSharpRunner: Starting CSharpBackend!
16/10/06 14:56:42 INFO CSharpRunner: Port number used by CSharpBackend is 5567
***********************************************************************
* [CSharpRunner.main] Backend running debug mode. Press enter to exit *
***********************************************************************
16/10/06 14:56:59 INFO SparkContext: Running Spark version 2.0.0
16/10/06 14:56:59 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/10/06 14:56:59 INFO SecurityManager: Changing view acls to: ramkumarr
16/10/06 14:56:59 INFO SecurityManager: Changing modify acls to: ramkumarr
16/10/06 14:56:59 INFO SecurityManager: Changing view acls groups to:
16/10/06 14:56:59 INFO SecurityManager: Changing modify acls groups to:
16/10/06 14:56:59 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(ramkumarr); groups with view permissions: Set(); users  with modify permissions: Set(ramkumarr); groups with modify permissions: Set()
16/10/06 14:56:59 INFO Utils: Successfully started service 'sparkDriver' on port 61811.
16/10/06 14:56:59 INFO SparkEnv: Registering MapOutputTracker
16/10/06 14:56:59 INFO SparkEnv: Registering BlockManagerMaster
16/10/06 14:57:00 INFO DiskBlockManager: Created local directory at C:\Users\ramkumarr\AppData\Local\Temp\blockmgr-284cacf9-39ee-4167-85a6-ddb2086b6585
16/10/06 14:57:00 INFO MemoryStore: MemoryStore started with capacity 117.0 MB
16/10/06 14:57:00 INFO SparkEnv: Registering OutputCommitCoordinator
16/10/06 14:57:00 INFO Utils: Successfully started service 'SparkUI' on port 4040.
16/10/06 14:57:00 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://192.168.43.168:4040
16/10/06 14:57:00 INFO Executor: Starting executor ID driver on host localhost
16/10/06 14:57:00 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 61820.
16/10/06 14:57:00 INFO NettyBlockTransferService: Server created on 192.168.43.168:61820
16/10/06 14:57:00 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 192.168.43.168, 61820)
16/10/06 14:57:00 INFO BlockManagerMasterEndpoint: Registering block manager 192.168.43.168:61820 with 117.0 MB RAM, BlockManagerId(driver, 192.168.43.168, 61820)
16/10/06 14:57:00 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 192.168.43.168, 61820)
16/10/06 14:57:01 ERROR CSharpBackendHandler: methods:
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static scala.collection.Seq org.apache.spark.sql.api.csharp.SQLUtils.toSeq(java.lang.Object)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static org.apache.spark.sql.SQLContext org.apache.spark.sql.api.csharp.SQLUtils.getSqlContext(org.apache.spark.sql.SparkSession)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static org.apache.spark.rdd.RDD org.apache.spark.sql.api.csharp.SQLUtils.dfToRowRDD(org.apache.spark.sql.Dataset)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static byte[][] org.apache.spark.sql.api.csharp.SQLUtils.dfToCols(org.apache.spark.sql.Dataset)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static org.apache.spark.sql.Dataset org.apache.spark.sql.api.csharp.SQLUtils.loadTextFile(org.apache.spark.sql.SQLContext,java.lang.String,java.lang.Boolean,java.lang.Boolean)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static org.apache.spark.sql.Dataset org.apache.spark.sql.api.csharp.SQLUtils.loadTextFile(org.apache.spark.sql.SQLContext,java.lang.String,java.lang.String,java.lang.String)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static org.apache.spark.sql.SaveMode org.apache.spark.sql.api.csharp.SQLUtils.saveMode(java.lang.String)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static org.apache.spark.sql.types.StructType org.apache.spark.sql.api.csharp.SQLUtils.createSchema(java.lang.String)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static org.apache.spark.sql.Dataset org.apache.spark.sql.api.csharp.SQLUtils.loadDF(org.apache.spark.sql.SQLContext,java.lang.String,java.util.Map)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static org.apache.spark.sql.Dataset org.apache.spark.sql.api.csharp.SQLUtils.loadDF(org.apache.spark.sql.SQLContext,java.lang.String,org.apache.spark.sql.types.StructType,java.util.Map)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static org.apache.spark.sql.Dataset org.apache.spark.sql.api.csharp.SQLUtils.loadDF(org.apache.spark.sql.SQLContext,java.lang.String,org.apache.spark.sql.types.StructType)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static byte[] org.apache.spark.sql.api.csharp.SQLUtils.colToCSharpBytes(java.lang.Object[])
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static java.lang.Object[][] org.apache.spark.sql.api.csharp.SQLUtils.convertRowsToColumns(org.apache.spark.sql.Row[],int)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static org.apache.spark.sql.SparkSession org.apache.spark.sql.api.csharp.SQLUtils.createSparkSession(org.apache.spark.SparkContext)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static org.apache.spark.sql.SparkSession org.apache.spark.sql.api.csharp.SQLUtils.getSparkSession(org.apache.spark.sql.SQLContext)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static org.apache.spark.api.python.PythonFunction org.apache.spark.sql.api.csharp.SQLUtils.createCSharpFunction(byte[],java.util.Map,java.util.List,java.lang.String,java.lang.String,java.util.List,org.apache.spark.Accumulator)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static org.apache.spark.sql.types.DataType org.apache.spark.sql.api.csharp.SQLUtils.getSQLDataType(java.lang.String)
16/10/06 14:57:01 ERROR CSharpBackendHandler: public static org.apache.spark.api.java.JavaSparkContext org.apache.spark.sql.api.csharp.SQLUtils.getJavaSparkContext(org.apache.spark.sql.SQLContext)
16/10/06 14:57:02 ERROR CSharpBackendHandler: public static org.apache.spark.rdd.RDD org.apache.spark.sql.api.csharp.SQLUtils.byteArrayRDDToAnyArrayRDD(org.apache.spark.api.java.JavaRDD)
16/10/06 14:57:02 ERROR CSharpBackendHandler: public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException
16/10/06 14:57:02 ERROR CSharpBackendHandler: public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException
16/10/06 14:57:02 ERROR CSharpBackendHandler: public final void java.lang.Object.wait() throws java.lang.InterruptedException
16/10/06 14:57:02 ERROR CSharpBackendHandler: public boolean java.lang.Object.equals(java.lang.Object)
16/10/06 14:57:02 ERROR CSharpBackendHandler: public java.lang.String java.lang.Object.toString()
16/10/06 14:57:02 ERROR CSharpBackendHandler: public native int java.lang.Object.hashCode()
16/10/06 14:57:02 ERROR CSharpBackendHandler: public final native java.lang.Class java.lang.Object.getClass()
16/10/06 14:57:02 ERROR CSharpBackendHandler: public final native void java.lang.Object.notify()
16/10/06 14:57:02 ERROR CSharpBackendHandler: public final native void java.lang.Object.notifyAll()
16/10/06 14:57:02 ERROR CSharpBackendHandler: args:
16/10/06 14:57:02 ERROR CSharpBackendHandler: argType: org.apache.spark.SparkContext, argValue: org.apache.spark.SparkContext@9c82d

**Comment by skaarthik** [comment] 2016-10-06 22:36
@ramkumarravy Thanks for the logs. It seems like Hive functionality was broken during Spark 2.0 upgrade. Expect a PR with the fix soon. Once it is merged with the master branch, you could build Mobius from master or wait for the next PREVIEW release. Note that Hive functionality should work fine in 1.6.* releases.

**Comment by ramkumarravy** [comment] 2016-10-07 04:59
Thanks for the reply.... Could you please let me know whether Mobius supports Spark ML/MLlib APIs ?

**Comment by skaarthik** [comment] 2016-10-07 20:24
Spark ML API is not available in Mobius now. If you need it, please add your comments to https://github.com/Microsoft/Mobius/issues/554. Someone will pick it up or better yet consider contributing to Mobius.

**Comment by skaarthik** [comment] 2016-10-08 00:55
Ramkumar - the issue with HiveDataFrame example is fixed in https://github.com/Microsoft/Mobius/commit/edd7b7fd8b73190dcf5c254ae1342fda43dee835.

Check out using Mobius with Hive using the SparkSession and deprecated HiveContext API in this PR (https://github.com/skaarthik/Mobius/blob/34567724738ce095c268c8e1408a48504cb440bc/examples/Sql/HiveDataFrame/Program.cs). You can build Mobius from master branch to use this Hive example. This PR will be merged to master branch after the latest code from master branch (including SparkSession) is included in the next PREVIEW release (which will be referenced in packages.config of the example).

**Comment by skaarthik** [comment] 2016-10-11 23:48
Fix (https://github.com/Microsoft/Mobius/commit/edd7b7fd8b73190dcf5c254ae1342fda43dee835) is in `master` and `branch-2.0` branches. It is also included in the latest preview release https://github.com/Microsoft/Mobius/releases/tag/v2.0.000-PREVIEW-2

**Closed by skaarthik** 2016-10-11 23:48 UTC
